name: Manual Mob Madness

on:
  workflow_dispatch:
    #inputs:

jobs:
  apk:
    name: Mobile Security Framework
    runs-on: ubuntu-latest
    steps:

      - name: Run MobSF
        run: |
          docker pull opensecurity/mobile-security-framework-mobsf
          docker run -itd -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest 
          cd build/app/outputs/flutter-apk/
          ls -al
          wget http://localhost:8000/api_docs
          MOBSF_API_KEY=$(grep 'REST API Key' api_docs)
          MOBSF_API_KEY=${MOBSF_API_KEY:42:64}
          rm api_docs
          HASH=$(md5sum remote.apk)
          HASH=${HASH:0:32}
          curl -F "file=@remote.apk" http://localhost:8000/api/v1/upload -H "Authorization:$MOBSF_API_KEY"
          curl -X POST --url http://localhost:8000/api/v1/scan --data "scan_type=apk&file_name=remote.apk&hash=$HASH" -H "Authorization:$MOBSF_API_KEY"
          curl -X POST --url http://localhost:8000/api/v1/download_pdf --data "hash=$HASH" -H "Authorization:$MOBSF_API_KEY" --output ${{ steps.build_id.outputs.id }}-security-scan.pdf
          ls -al

      #- name: Upload Security Report
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: diagrams
      #    path: diagrams/diagram*
