name: Release

on:
  release:

jobs:
  #apk:
    #name: Release APK
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v2
    #- uses: actions/setup-java@v1
    #  with:
    #    java-version: '12.x'
    #- uses: subosito/flutter-action@v1
    #  with:
    #    channel: 'stable' # 'dev', 'alpha', default to: 'stable'
    #- run: flutter pub get
    #- run: flutter build apk
    #- run: cd build/app/outputs && tree
    #- name: Upload binaries to release
    #  uses: svenstaro/upload-release-action@v2
    #  with:
    #    repo_token: ${{ secrets.GITHUBTOKEN }}
    #    file: build/app/outputs/flutter-apk/*
    #    tag: ${{ github.ref }}
    #    overwrite: true
    #    file_glob: true
  iOS:
    name: Release iOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - run: brew install tree
    - run: |
        cd /Users/runner/work/flutter-webview/flutter-webview/build/ios/iphoneos
        tree
        ls -al
        mkdir Payload
        mv Runner.app Payload/Runner.app
        tar -zcvf Payload.ipa Payload

        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUBTOKEN }}
        file: /Users/runner/work/flutter-webview/flutter-webview/build/ios/iphoneos/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
